let mock = [{
    id: "jlk43",
    book: "1 Nephi",
    chapter: "3",
    verse: "7",
    content: "And it came to pass that I, Nephi, said unto my father: I will go and do the things which the Lord hath commanded, for I know that the Lord giveth no commandments unto the children of men, save he shall prepare a way for them that they may accomplish the thing which he commandeth them.",
    note: "",
  },
  {
    id: "jfsd0",
    book: "Ether",
    chapter: "12",
    verse: "27",
    content: "And if men come unto me I will show unto them their weakness. I give unto men weakness that they may be humble; and my grace is sufficient for all men that humble themselves before me; for if they humble themselves before me, and have faith in me, then will I make weak things become strong unto them.",
    note: "",
    topic: "",
  },
  {
    id: "f;lkj3",
    book: "2 Nephi",
    chapter: "2",
    verse: "25",
    content: "Adam fell that men might be; and men care, that they might have joy.",
    note: "",
    topic: "",
  },
  {
    id: "sdfc0",
    book: "2 Nephi",
    chapter: "31",
    verse: "20",
    content: "Wherefore, ye must press forward with a steadfastness in Christ, having a perfect brightness of hope, and a clove of God and of all men. Wherefore, if ye shall press forward, feasting upon the word of Christ, and endure to the end, behold, thus saith the Father: Ye shall have eternal life.",
    note: "",
    topic: "",
  },
  {
    id: "fe;lkj",
    book: "Mosiah",
    chapter: "2",
    verse: "17",
    content: "And behold, I tell you these things that ye may learn wisdom; that ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God.",
    note: "",
    topic: "",
  },
  {
    id: "sdf8",
    book: "Helaman",
    chapter: "5",
    verse: "12",
    content: "And now, my sons, remember, remember that it is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your bfoundation; that when the devil shall send forth his mighty winds, yea, his shafts in the whirlwind, yea, when all his hail and his mighty cstorm shall beat upon you, it shall have no power over you to drag you down to the gulf of misery and endless wo, because of the rock upon which ye are built, which is a sure foundation, a foundation whereon if men build they cannot fall.",
    note: "",
    topic: "",
  },

]

export default mock;
